apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: fhir-server-exporter
build:
  artifacts:
    - image: fhir-server-exporter
      docker:
        dockerfile: Dockerfile
  local:
    useBuildkit: true
deploy:
  kustomize: {}
