# yaml-language-server: $schema=https://raw.githubusercontent.com/GoogleContainerTools/skaffold/main/docs/content/en/schemas/v2beta28.json
apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: fhir-server-exporter
build:
  artifacts:
    - image: fhir-server-exporter
      docker:
        dockerfile: Dockerfile
  local:
    useBuildkit: true
deploy:
  kubectl:
    manifests:
      - hack/k8s/pods.yaml
