apiVersion: skaffold/v3
kind: Config
metadata:
  name: fhir-server-exporter
build:
  artifacts:
    - image: ghcr.io/chgl/fhir-server-exporter
      docker:
        dockerfile: Dockerfile
  local:
    useBuildkit: true
manifests:
  kustomize:
    paths:
      - .
