services:
  prometheus:
    image: quay.io/prometheus/prometheus:v2.51.0@sha256:5ccad477d0057e62a7cd1981ffcc43785ac10c5a35522dc207466ff7e7ec845f
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  fhir-server:
    image: docker.io/hapiproject/hapi:v7.0.3@sha256:73ff82fec42e5cbb7e66338d47af09ba91c140e98beeaee41a5459572d5ae1ce
    environment:
      HAPI_FHIR_MDM_ENABLED: "false"
    ports:
      - "127.0.0.1:8082:8080"

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7@sha256:14e99d6f5dd0516a5bdc82537b732cb85469ecdb15ad7fe5f11ff67521544db8
    environment:
      KEYCLOAK_ADMIN: admin
      # kics-scan ignore-line
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "127.0.0.1:8083:8080"
