services:
  download:
    image: docker.io/curlimages/curl:8.18.0@sha256:d94d07ba9e7d6de898b6d96c1a072f6f8266c687af78a74f380087a0addf5d17
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - ALL
    privileged: false
    restart: "no"
    entrypoint: ["/bin/sh", "-c"]
    working_dir: /downloads
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    command:
      - |
        curl -LO https://github.com/synthetichealth/synthea/releases/download/master-branch-latest/synthea-with-dependencies.jar
    volumes:
      - $PWD/bin:/downloads:rw

  synthea:
    image: docker.io/library/eclipse-temurin:21.0.7_6-jre-ubi9-minimal@sha256:be37f4233c179ca1f40e9c8d7974df1b6676b9599b375389b8e15e0218e34083
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - ALL
    privileged: false
    restart: "no"
    entrypoint: ["/bin/sh", "-c"]
    working_dir: /workspace
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    environment:
      SYNTHEA_SEED: "20250718"
    command:
      - |
        java -jar /workspace/bin/synthea-with-dependencies.jar -s $$SYNTHEA_SEED -cs $$SYNTHEA_SEED -r $$SYNTHEA_SEED -p 10 -c config/synthea.properties
    volumes:
      - $PWD/bin:/workspace/bin/:ro
      - $PWD/synthea:/workspace/synthea/:rw
      - $PWD/config:/workspace/config/:ro
    depends_on:
      download:
        condition: service_completed_successfully
