services:
  prometheus:
    image: quay.io/prometheus/prometheus:v2.36.0
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  fhir-server:
    image: docker.io/hapiproject/hapi:v5.7.0
    environment:
      HAPI_FHIR_MDM_ENABLED: "false"
    ports:
      - "127.0.0.1:8082:8080"

  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "127.0.0.1:8083:8080"
