version: "3.7"

services:
  prometheus:
    image: prom/prometheus:v2.27.1
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  fhir-server:
    image: ghcr.io/chgl/hapifhir/hapi-fhir-jpaserver-starter:5.5.0-pre1-snapshot
    ports:
      - "127.0.0.1:8082:8080"

  keycloak:
    image: quay.io/keycloak/keycloak:13.0.1
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "127.0.0.1:8083:8080"
