services:
  prometheus:
    image: quay.io/prometheus/prometheus:v2.38.0@sha256:aa1687dd552ed98df598cc0fed2effbc62a0f05236bc2253c65520ddd4f2afce
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  fhir-server:
    image: docker.io/hapiproject/hapi:v6.0.1
    environment:
      HAPI_FHIR_MDM_ENABLED: "false"
    ports:
      - "127.0.0.1:8082:8080"

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "127.0.0.1:8083:8080"
