version: "3.7"

services:
  prometheus:
    image: prom/prometheus:v2.25.0
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  fhir-server:
    image: hapiproject/hapi:v5.2.0
    ports:
      - "127.0.0.1:8082:8080"
