apiVersion: batch/v1
kind: Job
metadata:
  name: test-fhir-server-exporter
spec:
  template:
    spec:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: curl
          image: docker.io/curlimages/curl:8.22.0@sha256:58adaa4e8dca9c988bae2aba4ab3434a0bb2da16bbe3f92dec39ec7785166777
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - "ALL"
            privileged: false
            runAsGroup: 65532
            runAsUser: 65532
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          command: ["/bin/sh", "-c"]
          args:
            - curl
              --retry-connrefuse
              --connect-timeout 10
              --max-time 300
              --retry 10
              --retry-delay 10
              http://fhir-server-exporter:9797/metrics
      restartPolicy: Never
